#!/bin/bash

if [ "$EUID" -eq 0 ]
then
        echo -e "Do not run the script as root!\nScript stopped!"
        exit
fi

# Functions that add the custom configs
customconfigs=$(dirname "$0")/../../configs
### bash
AddBash()
{
	cp -r $customconfigs/bash/. ~/
	#source ~/.bashrc  #Need to make this work!!
	echo "Bash config updated!"
}
### nvim
AddNvim()
{
	mkdir -p ~/.config/nvim
	cp -r $customconfigs/nvim/. ~/.config/nvim/
	echo "Nvim config updated!"
}
### sway
AddSway()
{
	mkdir -p ~/.config/sway
	cp -r $customconfigs/sway/. ~/.config/sway/
	swaymsg reload
	echo "Sway config updated!"
}
### waybar
AddWaybar()
{
	mkdir -p ~/.config/waybar
	cp -r $customconfigs/waybar/. ~/.config/waybar/
	swaymsg reload
	echo "Waybar config updated!"
}
### eww
AddEww()
{
	mkdir -p ~/.config/eww
	cp -r $customconfigs/eww/. ~/.config/eww/
	eww reload
	echo "Eww config updated!"
}

if [ "$1" == "--update-all" ]; then
	AddBash
	AddNvim
	AddSway
	AddWaybar
	AddEww
elif [ "$1" == "--update" ]; then
	"Add"$2
fi
